Added Optifine, PackMenu, Loaded into world bad fps
Optifine adds +4 minutes to start process. It's not stuck, apparently.

When loading world with optifine game crash?
bad json: create_stuff_additions:recipes/tungsten_ingot_recipe_3.json L17c4 and many other recipes.

Parsing error loading recipe empatic:smeltery/casting/cloggrum/ingot_sand

Parsing error loading recipe psg:modprova
com.google.gson.JsonSyntaxException: Unknown item 'charm:sugar_block' and *many* more all from "byg"

Actual crash probably caused by chunkloader with ticketing system (NoSuchMethod: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)')